### ISSUE TITLE
Game window not parented to the tool

### ISSUE THREAD

**Issue by jean-knapp** [jean-knapp/windows-source-modding-tool#15]
official counter-strike fanclub
i didnt know launching the game would launch it in the program, props for that
granted in my case its in a corner, but impressive
![image](https://user-images.githubusercontent.com/54725233/72224886-95351e00-3555-11ea-9d26-ddbe492b9815.png)
yeah that might be something to do for slow loading games like gmod
![image](https://user-images.githubusercontent.com/54725233/72224891-a120e000-3555-11ea-96d2-060dd724ee69.png)
as you can see, it never parented
also it likes to throw me a expection when i move the window while gmod is like that

`************** Exception Text **************
System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at SourceModdingTool.SourceSDK.Game.Resize()
   at SourceModdingTool.MainForm.ModForm_ResizeEnd(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnResizeEnd(EventArgs e)
   at System.Windows.Forms.Form.WmExitSizeMove(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by jean-knapp** [comment]
I probably fixed this. We need to check if this happens again.
